widgetTheme=widget-themes/original
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=cemalkuller@gmail.com
loadingLabel=Yükleniyor...
loginError=Giriş Hatası
chatHeader=Canlı Destek
startInfo=Merhaba Size Nasıl Yardımcı Olabiliriz?
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/New Message I.mp3
startLabel=Başlat
backLabel=Geri
initMessageBody=Merhaba, Size Nasıl Yardımcı Olabiliriz.
initMessageAuthor=Temsilci
chatInputLabel=Soru Sorun
timeDaysAgo=gün önce
timeHoursAgo=saat önce
timeMinutesAgo=dakika önce
timeSecondsAgo=saniye önce
offlineMessage=Temsilci Çevrimdışı
toggleSoundLabel=Ses Efekti
toggleScrollLabel=Otomatik Kaydırma
toggleEmoticonsLabel=Emoji
toggleAutoShowLabel=Otomatik Gösterim
toggleFullscreenLabel=Full Ekran
endChatLabel=Sohbeti Sonlandır
endChatConfirmQuestion=Emin misiniz?
endChatConfirm=Evet
endChatCancel=Vazgeç
contactHeader=İletişim
contactInfo=Tüm operatörler kapalı. Sorunuzu içeren bir e-posta göndermek için aşağıdaki formu kullanın.
contactNameLabel=İsim Soyisim
contactMailLabel=E-Posta Adresi
contactQuestionLabel=Sorunuz
contactSendLabel=Gönder
contactSuccessHeader=Mesajınız Gönderildi
contactSuccessMessage=Sorunuz Başarılı Bir Şekilde Gönderildi
contactErrorHeader=Hata
contactErrorMessage= Sorunuzu gönderirken bir hata oluştu
headerHeight=55
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
